### ISSUE TITLE
Client status is always - online

### ISSUE THREAD

**Issue by alexsahka** [gamebeast2k/docker_traccar2mqtt#4] opened 2021-01-06 17:58 UTC
Client status is always - online, in the MQTT. 
Even if the client status goes to Unknown or Offline in the Traccar interface.

**Comment by gamebeast2k** [comment] 2021-01-08 15:14
I have check it and yes the client status never changed.
The problem is that Traccar forward only ONLINE events. So traccart2mqtt dont know that the device is offline.
A Workaround is to use the lastUpdate state in mqtt. Maybe like this if(time()-lastupdate > 300sec) = offline //5min no update

Sorry

**Comment by alexsahka** [comment] 2021-01-08 16:20
Thank you! I suspect there something to do with the Traccar setting file, I saw a few conversations on the Traccar forum on this topic. Thanks for the suggestion I thought about this, actually, it is easy to do (I'm using NodeRed). I asked this question only for one reason if you can check your code. Now, I need to find out if I can change somehow Traccar setting. One more time, thank you!

**Comment by alexsahka** [comment] 2022-01-27 02:04
The Traccar server API (after a few updates) shows the status: "unknown" when the client is not online, but the MQTT status is always - online. I think now traccar2mqtt is not working properly to show client status. 

Is it possible to fix this issue now? Traccar server API function as it shud.
Thanks.

**Comment by gamebeast2k** [comment] 2022-03-30 10:06
sorry for the long delay but Corona hit my famaly/friends hard. 
I have look into it and yes **json.device.status** get the state "unknown"/"online" but only via Event Forward.

I read something and think in a few days should be a solution there.

**Comment by gamebeast2k** [comment] 2022-03-30 11:24
fixed in 1297cfe3c5b1d62a3b7a68f7e05b348506d7b635

**Closed as completed** 2022-05-01 17:21 UTC
Labels: enhancement

**Comment by alexsahka** [comment] 2022-08-21 06:20
Could you push the update to https://hub.docker.com/ ?

I can see the latest image is 5 months old.

Thank you!

![image](https://user-images.githubusercontent.com/7469537/185778393-d8bb9e36-d7d4-4e2a-8c01-f17d4a793c3e.png)

**Comment by gamebeast2k** [comment] 2022-08-21 12:15
Hi, thx for the Info. Build comes today.

**Comment by gamebeast2k** [comment] 2022-08-21 12:24
New Image pushed.

Have Fun.

**Comment by alexsahka** [comment] 2022-08-21 16:36
Thank you!

**Comment by alexsahka** [comment] 2022-08-22 04:09
I was experimenting with the updated container and I was satisfied with my device when I disable the tracking app the MQTT posting traccar/.../status = unknown what exactly we wanted and matched what I see in the API.
But later I noticed 2 other devices lost cellular connection (they are out of mobile coverage) but MQTT still posting status = online
And when I checked the status in the API it was status = unknown so I think something not working correctly, it is weird that on my device when I disabled the application after 15 minutes MQTT posted the correct status matching the API.

Maybe I am wrong but seems like the first client status is working fine but not the rest of the clients.

Also another problem with the geofenceIds it seems like the last geofenceIds stay forever if the device is not entered into other geofenceIds. So it updates fine if the device enters the zone but the geofenceIds never change to null if the device is out of geofenceIds.  API publishing =null at the time

**Comment by gamebeast2k** [comment] 2022-08-22 10:32
Okay. I understand. 
Please check the Blank JSON publish! Same issue?
```
traccar/#/position/json < check this for geofenceids
traccar/#/device/json < check this for state issue
tracar/#/event/json
```
have you looked to see if "traccar/#/event/geofenceId" and "traccar/#/geofenceIds" have the same problem ?
